# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20161121_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['gift_number']},
        ),
    ]
