# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
