# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20171130_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triviachoices',
            options={'ordering': ['question', 'number']},
        ),
    ]
