# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20171207_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=60)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.TriviaQuestion')),
            ],
            options={
                'ordering': ['question', 'number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='triviachoice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='triviachoice',
            name='question',
        ),
        migrations.AlterField(
            model_name='triviauserresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.TriviaChoices'),
        ),
        migrations.DeleteModel(
            name='TriviaChoice',
        ),
        migrations.AlterUniqueTogether(
            name='triviachoices',
            unique_together=set([('question', 'number')]),
        ),
    ]
