# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_auto_20171207_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TriviaChoices',
            new_name='TriviaChoice',
        ),
    ]
