# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_auto_20171207_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviachoice',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
