# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='response',
            old_name='author',
            new_name='responder',
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='entered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='response',
            field=models.TextField(default='Test Question'),
            preserve_default=False,
        ),
    ]
