# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20171026_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['date']},
        ),
    ]
