# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trivia_answers_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trivia_questions_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
